### ISSUE TITLE
Still in devop. ? 

### ISSUE THREAD

**Issue by SilenLoc** [ratdoux/easyreading#12]
I am interested in maintaining this repo and contributing if it is still maintained by you @ratdoux.

I think the idea is good and I would propose to extend the idea into the following:

1. exclude and APIfy the logic, like that we can use any language to do the "text -> bionic text", or other "easy reading" logic.

> somthing like a protocol to just give text as input  and return a definition which characters should be changed. Like that you could, depending on the platform, use it as a mask, converter, highlighter or whatever. 

2. Create a roadmap for "easyrading" that would extends into roadmaps for "bionic reading" which would extends into a roadmap for "bionic reading platform x"

For now it would be:

# easyreading
### bionic reading chrome extension

Extensions for safari / firefox would be nice too.

I think it would be a really good thing to have open source accessibility software with a focus on ND and extending. 
 
Also: Since the logic is not rocket sience many open source beginners would sure like to contribute. 

FYI @ratdoux: I came here because your post on reddit :)

**Comment by ratdoux** [comment]
You do have good ideas, but sadly I'm not maintaining this anymore, nor will I maintain it in the future.

If you'd like, you can fork it and make it yours though!
