### ISSUE TITLE
Single page apps don't seem to like the extension

### ISSUE THREAD

**Issue by ratdoux** [ratdoux/easyreading#6]
Need to reload the page for the extension to apply on SPA's

**Comment by ratdoux** [comment]
or server rendered for that matter

**Comment by ratdoux** [comment]
@ModisR 

If you have an idea on how to get this to work, i'm all ears.

here's what i have tried for now

**Comment by ModisR** [comment]
Very nice work on the mutation observer, @neb42. Love that solution.
